# Generated by Django 5.2.1 on 2026-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion_fiscal',
            field=models.CharField(blank=True, default='', help_text="Dirección que aparece en el RTU del cliente. Si está vacía se usa 'direccion'.", max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nit',
            field=models.CharField(blank=True, default='CF', help_text="NIT del cliente. 'CF' para Consumidor Final (facturación sin NIT nominal).", max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_fiscal',
            field=models.CharField(blank=True, default='', help_text='Razón social o nombre como aparece en el NIT. Si está vacío se usa el nombre del usuario.', max_length=255),
        ),
    ]
