# Generated by Django 5.2.1 on 2026-04-25 18:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_direccion_fiscal_perfil_nit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(db_index=True, help_text='NIT de la empresa (sin espacios). Único en el sistema.', max_length=20, unique=True)),
                ('razon_social', models.CharField(help_text='Razón social como aparece en el RTU de SAT.', max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, default='', help_text='Nombre comercial / fantasía. Si está vacío se usa la razón social.', max_length=255)),
                ('direccion_fiscal', models.CharField(help_text='Dirección que aparece en el RTU.', max_length=500)),
                ('email_cobro', models.EmailField(blank=True, default='', help_text='Correo donde se envían facturas, estados de cuenta y recordatorios de cobro.', max_length=254)),
                ('contacto_principal', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('dias_credito', models.PositiveIntegerField(choices=[(0, 'Contado (0 días)'), (8, '8 días'), (15, '15 días'), (30, '30 días'), (45, '45 días'), (60, '60 días'), (90, '90 días')], default=30, help_text='Días de plazo desde la emisión hasta el vencimiento de cada factura.')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto máximo de saldo pendiente permitido. 0 = sin límite.', max_digits=12)),
                ('recordatorios_activos', models.BooleanField(default=True, help_text='Si está activo, se envían correos automáticos de recordatorio de cobro.')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se permiten nuevas facturas a crédito (solo override de admin).')),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa (Cliente Corporativo)',
                'verbose_name_plural': 'Empresas (Clientes Corporativos)',
                'ordering': ['razon_social'],
            },
        ),
    ]
