# Generated by Django 5.2.1 on 2026-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_id', models.CharField(choices=[('citas_recordatorios_diario', 'Recordatorios de citas'), ('cxc_recordatorios_diario', 'Recordatorios de cobro CxC'), ('inventario_resumen_am', 'Resumen de inventario (AM)'), ('inventario_resumen_pm', 'Resumen de inventario (PM)')], help_text='Identificador interno del job (estable).', max_length=64, unique=True)),
                ('nombre', models.CharField(help_text='Nombre legible para mostrar en la UI.', max_length=128)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción de qué hace la tarea cuando se ejecuta.')),
                ('hora', models.TimeField(help_text='Hora local (America/Guatemala) en que la tarea corre cada día.')),
                ('habilitada', models.BooleanField(default=True, help_text='Si está deshabilitada, el job se remueve del scheduler.')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ultima_ejecucion_status', models.CharField(blank=True, choices=[('OK', 'Éxito'), ('ERROR', 'Error')], default='', max_length=16)),
                ('ultima_ejecucion_mensaje', models.TextField(blank=True, default='', help_text='Mensaje breve del último intento (error o resumen).')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['nombre'],
            },
        ),
    ]
