# Generated by Django 5.2.1 on 2026-04-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_seed_tareas_programadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to='usuarios/avatares/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_pendiente',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
