# Generated by Django 5.2.1 on 2026-04-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email de login al panel SaaS', max_length=254, unique=True, verbose_name='email')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('password', models.CharField(max_length=128, verbose_name='password hash')),
                ('rol', models.CharField(choices=[('superadmin', 'Superadmin (todo)'), ('soporte', 'Soporte técnico'), ('ventas', 'Ventas / comercial')], default='superadmin', max_length=20, verbose_name='rol')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='último login')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario SaaS',
                'verbose_name_plural': 'Usuarios SaaS',
                'ordering': ['nombre'],
            },
        ),
    ]
