# Generated by Django 5.2.1 on 2026-04-29 00:28

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre', models.CharField(help_text='Ej. "Fixfast Pro Taller Mecánico"', max_length=100, verbose_name='nombre comercial')),
                ('slug', models.SlugField(help_text='Identificador en URL. Ej. "fixfast" → fixfast.autoservipro.com', unique=True, verbose_name='slug')),
                ('email_contacto', models.EmailField(help_text='Email del dueño del taller para soporte y facturación del SaaS', max_length=254, verbose_name='email de contacto')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, los logins al subdomain retornan 403', verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('trial_hasta', models.DateField(blank=True, help_text='Fecha en la que vence el trial. Vacío = sin trial (plan de pago)', null=True, verbose_name='trial hasta')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
