# Generated by Django 5.2.1 on 2026-04-14 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='nivel_gasolina',
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='diagrama_danos',
            field=models.TextField(blank=True, help_text='Base64 del diagrama táctil trazado', null=True),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='estado_cristales',
            field=models.CharField(blank=True, help_text='Ej: Parabrisas estrellado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='estado_fluidos',
            field=models.JSONField(blank=True, default=dict, help_text="Ej: {'aceite': 'Nivel Bajo', 'refrigerante': 'OK'}"),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='firma_digital',
            field=models.TextField(blank=True, help_text='Base64 de la firma táctil digital', null=True),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='gasolina_pct',
            field=models.PositiveIntegerField(default=50, help_text='Porcentaje de gasolina (0-100)'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='luces_tablero',
            field=models.JSONField(blank=True, default=dict, help_text="Ej: {'check_engine': true, 'abs': false}"),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='danos_previos',
            field=models.TextField(blank=True, help_text='Notas adicionales de daños', null=True),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='firma_cliente_text',
            field=models.CharField(blank=True, help_text='Nombre escrito como firma de conformidad.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RecepcionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='recepciones/fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='citas.recepcionvehiculo')),
            ],
        ),
    ]
