# Generated by Django 5.2.1 on 2026-04-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_recepcionvehiculo_nivel_gasolina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='unidad_distancia',
            field=models.CharField(choices=[('km', 'Kilómetros'), ('mi', 'Millas')], default='km', max_length=10),
        ),
    ]
