# Generated by Django 5.2.1 on 2026-04-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_recepcionvehiculo_unidad_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='firma_mecanico',
            field=models.TextField(blank=True, help_text='Base64 de la firma táctil digital del mecánico', null=True),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='firma_digital',
            field=models.TextField(blank=True, help_text='Base64 de la firma táctil digital del cliente', null=True),
        ),
    ]
