# Generated by Django 5.2.1 on 2026-04-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_recepcionvehiculo_firma_mecanico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='cilindrada_motor',
            field=models.CharField(blank=True, help_text='Ej: 2.0L o 2000cc', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(blank=True, help_text='Último kilometraje/millaje registrado', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('HIBRIDO', 'Híbrido'), ('ELECTRICO', 'Eléctrico')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(blank=True, choices=[('AUTOMATICA', 'Automática'), ('MECANICA', 'Mecánica'), ('CVT', 'CVT')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='unidad_medida_kilometraje',
            field=models.CharField(choices=[('KM', 'Kilómetros'), ('MI', 'Millas')], default='KM', max_length=2),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin_chasis',
            field=models.CharField(blank=True, help_text='VIN / Número de Chasis', max_length=50, null=True),
        ),
    ]
