# Generated by Django 5.2.1 on 2026-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_vehiculo_cilindrada_motor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_mecanico', models.PositiveIntegerField(default=3, help_text="Número de vehículos de mecánica que se pueden atender en paralelo (un 'slot' por cada mecánico disponible).")),
                ('capacidad_carwash', models.PositiveIntegerField(default=1, help_text='Número de vehículos de lavado que se pueden atender en paralelo.')),
                ('hora_apertura', models.TimeField(default='08:00', help_text='Hora a la que el taller empieza a recibir citas.')),
                ('hora_cierre', models.TimeField(default='18:00', help_text='Última hora a la que puede iniciar una cita (la cita puede terminar después, según su duración).')),
                ('granularidad_slot', models.PositiveIntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (60, '60 minutos')], default=30, help_text='Cada cuántos minutos se ofrece un slot en la agenda.')),
                ('dias_laborales', models.JSONField(default=list, help_text='Lista de días laborales (0=Lunes, 6=Domingo). Por defecto: Lun–Sáb.')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Taller',
                'verbose_name_plural': 'Configuración del Taller',
            },
        ),
    ]
