# Generated by Django 5.2.1 on 2026-04-25 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_configuraciontaller'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontaller',
            name='permitir_re_recepcion',
            field=models.BooleanField(default=False, help_text='Si está activo, una misma cita puede tener más de una recepción (por ejemplo, si el vehículo volvió a ingresar).'),
        ),
        migrations.AddField(
            model_name='configuraciontaller',
            name='requerir_recepcion_antes_trabajo',
            field=models.BooleanField(default=True, help_text="Si está activo, se pide confirmación al mover una OT de 'En Espera' a 'En Revisión' sin recepción registrada."),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='citas.cita'),
        ),
    ]
