# Generated by Django 5.2.1 on 2026-04-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_configuraciontaller_permitir_re_recepcion_and_more'),
        ('usuarios', '0004_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este vehículo (flota corporativa). Si se establece, las facturas pueden emitirse a la empresa en lugar del propietario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='usuarios.empresa'),
        ),
    ]
