# Generated by Django 5.2.1 on 2026-04-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_vehiculo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontaller',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del taller (PNG/JPG). Aparece en sidebar, login y facturas. Idealmente cuadrado o transparente.', null=True, upload_to='taller/logos/'),
        ),
        migrations.AddField(
            model_name='configuraciontaller',
            name='nombre_empresa',
            field=models.CharField(blank=True, default='', help_text="Nombre comercial del taller; se muestra en sidebar, login y facturas. Si está vacío se usa 'AutoServi'.", max_length=120),
        ),
    ]
