# Generated by Django 5.2.1 on 2026-04-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_configuraciontaller_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.SlugField(help_text="Identificador interno del evento (ej. 'cita_recordatorio').", max_length=64, unique=True)),
                ('label', models.CharField(help_text='Nombre humano del evento, mostrado en el panel de configuración.', max_length=120)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción opcional para el panel.', max_length=255)),
                ('grupo', models.CharField(default='General', help_text="Agrupa eventos en la UI (ej. 'Citas', 'Facturación', 'Inventario').", max_length=32)),
                ('email_activo', models.BooleanField(default=True, help_text='Si está activo, el evento dispara correo a destinatarios.')),
                ('whatsapp_activo', models.BooleanField(default=False, help_text='Si está activo, el evento dispara mensaje WhatsApp (Twilio).')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el panel.')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canal de notificación',
                'verbose_name_plural': 'Canales de notificación',
                'ordering': ['grupo', 'orden', 'label'],
            },
        ),
    ]
