# Generated by Django 5.2.1 on 2026-04-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_ordencompra_cancelada_por_ordencompra_cita_taller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT / RTU'),
        ),
    ]
