# Generated by Django 5.2.1 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_proveedor_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertainventario',
            name='notificado_in_app',
            field=models.BooleanField(default=False, help_text='Notificación in-app (campanita) ya creada para esta alerta.'),
        ),
    ]
