# Generated by Django 5.2.1 on 2026-03-21 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_recepcionvehiculo'),
        ('inventario', '0005_precioproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('EN_REVISION', 'En Revisión'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('LISTO', 'Listo para Entrega')], default='EN_ESPERA', max_length=20)),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico oficial del mecánico', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_trabajo', to='citas.cita')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='citas.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de usar el repuesto', max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_orden', to='inventario.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='taller.ordentrabajo')),
            ],
        ),
    ]
