# Generated by Django 5.2.1 on 2026-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('EN_REVISION', 'En Revisión'), ('COTIZACION', 'Cotización Enviada'), ('ESPERANDO_REPUESTOS', 'Esperando Repuestos'), ('LISTO', 'Listo para Entrega'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', max_length=20),
        ),
    ]
