# Generated by Django 5.2.1 on 2026-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenrepuesto',
            name='en_transito',
            field=models.BooleanField(default=False, help_text='Indica si fue agregado desde una Orden de Compra pero no ha llegado'),
        ),
    ]
