# Generated by Django 5.2.1 on 2026-04-04 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0002_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Pre-factura)'), ('EMITIDA', 'Emitida (Pagada/Cerrada)'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (Crédito/Débito)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTROS', 'Otros (Cheque, Cripto, etc.)')], max_length=15, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_pagada', models.DateTimeField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('orden', models.OneToOneField(help_text='La orden de trabajo restringirá el borrado si ya tiene factura.', on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
