# Generated by Django 5.2.1 on 2026-04-25 07:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='iva_incluido',
            field=models.BooleanField(default=True, help_text='Si está activo, los precios de mano de obra y repuestos ya tienen IVA incluido (desglose retrocalculado). Si está inactivo, el IVA se suma al total.'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.12'), help_text='Tasa de IVA aplicable. Guatemala General = 0.12, Pequeño Contribuyente = 0.05.', max_digits=5),
        ),
    ]
