# Generated by Django 5.2.1 on 2026-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_iva_incluido_factura_tasa_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_emisor', models.CharField(default='1234567-8', help_text='NIT del taller ante SAT (sin espacios, con guion si lo tiene). Ej: 1234567-8.', max_length=20)),
                ('nombre_fiscal', models.CharField(default='AutoServi Pro', help_text='Razón social exacta como aparece en tu RTU de SAT.', max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, default='AutoServi Pro', help_text='Nombre comercial (si es diferente de la razón social).', max_length=255)),
                ('direccion_fiscal', models.CharField(default='123 Calle Taller, Ciudad de Guatemala', max_length=500)),
                ('telefono', models.CharField(blank=True, default='+502 1234 5678', max_length=30)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('afiliacion_iva', models.CharField(choices=[('GEN', 'Contribuyente General (IVA 12%)'), ('PEQ', 'Pequeño Contribuyente (IVA 5%)')], default='GEN', help_text='Tipo de contribuyente. General usa IVA 12%, Pequeño usa 5%.', max_length=3)),
                ('establecimiento_codigo', models.PositiveIntegerField(default=1, help_text='Código del establecimiento dentro del NIT (normalmente 1 si solo tienes un local).')),
                ('serie_fel', models.CharField(default='A', help_text='Serie que asigna el certificador a tu emisor (la devuelve el proveedor al enrolarte).', max_length=20)),
                ('ambiente', models.CharField(choices=[('PRUEBAS', 'Pruebas (sandbox del certificador)'), ('PRODUCCION', 'Producción (factura real ante SAT)')], default='PRUEBAS', help_text='Mientras estés integrando, mantén PRUEBAS. Solo cambia a PRODUCCION con el certificador listo.', max_length=10)),
                ('certificador', models.CharField(blank=True, choices=[('', 'Sin definir'), ('INFILE', 'INFILE'), ('DIGIFACT', 'Digifact'), ('GUATEFACT', 'Guatefact'), ('MEGAPRINT', 'Megaprint'), ('OTRO', 'Otro')], default='', help_text='Proveedor que firma y envía tus DTE a SAT.', max_length=15)),
                ('certificador_api_url', models.URLField(blank=True, default='', help_text='URL base del API del certificador (te la da el proveedor).')),
                ('certificador_usuario', models.CharField(blank=True, default='', max_length=120)),
                ('certificador_api_key', models.CharField(blank=True, default='', help_text='Token / API key del certificador. Se usará al integrar Fase 4.', max_length=255)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuración de Facturación',
            },
        ),
    ]
