# Generated by Django 5.2.1 on 2026-04-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_configuracionfacturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(choices=[('FACT', 'Factura (FACT)'), ('NCRE', 'Nota de Crédito (NCRE)'), ('FCAM', 'Factura Cambiaria (FCAM)'), ('NDEB', 'Nota de Débito (NDEB)'), ('FPEQ', 'Factura Pequeño Contribuyente (FPEQ)')], default='FACT', max_length=5)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de certificar'), ('CERTIFICADO', 'Certificado por SAT'), ('ANULADO', 'Anulado ante SAT'), ('RECHAZADO', 'Rechazado por el certificador'), ('ERROR', 'Error en la comunicación')], default='PENDIENTE', max_length=15)),
                ('uuid_sat', models.CharField(blank=True, default='', max_length=50)),
                ('serie', models.CharField(blank=True, default='', max_length=20)),
                ('numero_autorizacion', models.CharField(blank=True, default='', max_length=50)),
                ('xml_generado', models.TextField(blank=True, default='', help_text='XML que enviamos al certificador.')),
                ('xml_certificado', models.TextField(blank=True, default='', help_text='XML firmado que devuelve el certificador.')),
                ('certificador_usado', models.CharField(blank=True, default='', max_length=20)),
                ('ambiente', models.CharField(blank=True, default='PRUEBAS', max_length=10)),
                ('errores', models.TextField(blank=True, default='')),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_certificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('documento_original', models.ForeignKey(blank=True, help_text='Para NCRE, apunta al FACT original que se corrige.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenciado_por', to='facturacion.documentoelectronico')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Documento Electrónico (DTE)',
                'verbose_name_plural': 'Documentos Electrónicos (DTE)',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
