# Generated by Django 5.2.1 on 2026-04-25 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_documentoelectronico'),
        ('usuarios', '0004_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito (B2B)')], default='CONTADO', help_text='CONTADO: pago inmediato. CREDITO: a plazo (solo permitido para Empresas).', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días de plazo desde fecha_emision (snapshot del valor en la empresa al momento de emitir).'),
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa cliente cuando la factura es a crédito B2B. Null para clientes individuales (contado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha calculada al emitir = fecha_emision + dias_credito. Solo aplica si condicion_pago=CREDITO.', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='override_motivo',
            field=models.TextField(blank=True, default='', help_text='Motivo registrado por el superadmin que aprobó facturar a crédito a pesar de que la empresa estaba bloqueada.'),
        ),
        migrations.AddField(
            model_name='factura',
            name='override_por',
            field=models.ForeignKey(blank=True, help_text='Superadmin que aprobó el override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_override', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='pago_estado',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica (contado)'), ('PENDIENTE', 'Pendiente de pago'), ('PARCIAL', 'Pago parcial recibido'), ('PAGADA', 'Pagada en su totalidad'), ('VENCIDA', 'Vencida (no pagada a tiempo)')], default='NO_APLICA', help_text='Estado de cobro. NO_APLICA = factura de contado. PENDIENTE/PARCIAL/PAGADA/VENCIDA = factura a crédito.', max_length=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Pre-factura)'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15),
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito Bancario'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=15)),
                ('referencia', models.CharField(blank=True, default='', help_text='Número de cheque, ID de transferencia, etc.', max_length=100)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, help_text='Fecha en la que el cliente realizó el pago (no la fecha en la que se registra).')),
                ('nota', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Facturas',
                'ordering': ['-fecha_pago', '-fecha_creacion'],
            },
        ),
    ]
