# Generated by Django 5.2.1 on 2026-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_factura_condicion_pago_factura_dias_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='envio_automatico_factura',
            field=models.BooleanField(default=True, help_text='Si está activo, al certificar una factura se envía por correo automáticamente al cliente o empresa.'),
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='recordatorios_cobro_auto',
            field=models.BooleanField(default=True, help_text='Si está activo, el sistema envía recordatorios de cobro automáticos a empresas con facturas a crédito (3 días antes / día / cada 7 días post-vencimiento).'),
        ),
    ]
