# Generated by Django 5.2.1 on 2026-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_configuracionfacturacion_envio_automatico_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfacturacion',
            name='certificador',
            field=models.CharField(blank=True, choices=[('', 'Sin definir'), ('FELPLEX', 'FELplex'), ('INFILE', 'INFILE'), ('DIGIFACT', 'Digifact'), ('GUATEFACT', 'Guatefact'), ('MEGAPRINT', 'Megaprint'), ('OTRO', 'Otro')], default='', help_text='Proveedor que firma y envía tus DTE a SAT.', max_length=15),
        ),
        migrations.AlterField(
            model_name='configuracionfacturacion',
            name='certificador_api_key',
            field=models.CharField(blank=True, default='', help_text='Token / API key del certificador (X-Authorization en FELplex).', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracionfacturacion',
            name='certificador_usuario',
            field=models.CharField(blank=True, default='', help_text='Usuario del certificador. Para FELplex = Entity ID (visible en tu panel PLEXapps).', max_length=120),
        ),
    ]
